spring:
  liquibase:
    enabled: true
  jpa:
    hibernate:
      show-sql: true
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/champagne
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver